# ETK CONIFIG GT5P DAYTONA STABLE BASELINE
Audio:
   # OpenSL or Cubeb or ALSA
  Renderer: ALSA
  # Downmix to Stereo to save SPU mixing cycles
  Channels: 2.0
  Audio Format: Stereo
  Audio Provider: CellAudio
  # Increasing buffer to tolerate SPU jitter
  Audio Buffer: 380
  Desired Audio Buffer Duration: 380
  Enable Buffering: true
  Time Stretching Threshold: 380
  Enable Time Stretching: true
Core:
  # Seems optimal at 2
  PPU Threads: 2
  # We need an extra thread for SPU-Audio synthesis
  Preferred SPU Threads: 3
  # Try switching between Mega and Safe - makes a big difference
  SPU Block Size: Mega
  # Approximate accuracy is mandatory to keep audio sync on SM8250
  SPU XFloat Accuracy: Approximate
  # We want SPU threads fast, but not starving the PPU
  Lower SPU Priority: false
Video:
  # Vulkan required for MESA Turnip
  Renderer: ALSA
  Resolution: 1280x720
  # Attempt 50% 66% 75% during extreme harvesting duress
  Resolution Scale: 100
  # Adreno tuned
  Resolution Scale Threshold: 512
  # Buffers
  Write Color Buffers: false
  Read Color Buffers: false
  Read Depth Buffer: false
  Write Depth Buffer: false
  Strict Rendering Mode: false
  Shader Mode: Async (with Shader Interpreter)
  Shader Precision: Low
  # Enable Frame Limit to 30 to prevent the CPU from over-reaching
  Frame limit: 30
  Aspect ratio: 16:9
  Output Scaling Mode: Bilinear
  VSync: false
  Multithreaded RSX: true
  RSX FIFO Accuracy: Ordered
  ZCULL Accuracy: Relaxed
  Vblank Frequency: 60Hz
  Relaxed ZCULL Sync: true
  Vulkan:
    Asynchronous Texture Streaming: true
